backend:
  name: git-gateway
  branch: main

media_folder: "dist/media"
public_folder: "/media"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/md"
    create: true
    slug: "{{year}}-{{month}}"
